### PR TITLE
Review solo project with the use of bootstrap classes

### PR DESCRIPTION
**Pull request by majovanilla**
The bootstrap solo project includes:

- [x] ReadMe file with extensive details about the project and links to original sources and contact information of the author.

- [x] Use of bootstrap classes whenever was possible and edit some of them with local CSS.

- [x] Responsive site with bootstrap breakpoints.

- [x] The site looks exactly as original except for the toggle menu display.

- [x] Fixed linters.

### CODE REVIEW

**Review by Ispirett — APPROVED** [review]
Excellent!! work with this project @majovainilla image

**There is just this one issue to fix and then you can merge!!**
This happens around 777px

current

**Comment by ebukaume** [comment]
Hi @majovainilla :wave: 

You have really done a good job with this project so far. Your commit and PR messages are good and descriptive, keep that up, please. Also, your README looks good :+1:. Don't forget to update the link to the live version later.

However, there a few things you missed. 

- [x] Check HTML markup with this validator https://validator.w3.org/#validate_by_upload and fix all errors
- [x] Comments: It’s better to delete commented code. If you need to review a previous version of your code, use git history.

**@majovainilla kindly submit another code review request form after you have fixed those issues.** :v:

**Comment by majovanilla** [comment]
Changed HTML error using the validator:

- [x] Error indicating that a <h> tag couldn't be inside a <il> or a <div>. I changed the h7 and h8 to <p>

- [x] Due to the last change, I get a warning indicating that my <article> has no heading. I left it like that because if I add a heading I get the error:  "Element h7 not allowed as child of element article in this context."

- [x] Deleted commented code on the CSS file.

**Comment by ebukaume** [comment]
Hi @majovainilla  :wave: 

Nice job removing the errors deleting commented codes. Your project is now good to go. :+1: 

**Go ahead and merge into master!**

[OPTIONAL]
You can refer to [this](https://www.w3.org/wiki/HTML/Usage/Headings/Missing) for why you may need to clear the remaining warnings. It helps your page accessibility.

**Congratulations. Good luck with your next project.** :wine_glass:

**Comment by majovanilla** [comment]
The last commit includes the changes to the HTML file to avoid warnings.
Now, every article includes a heading.

**Pull request merged**
